version: '3.5'

services:
  postgres:
    image: postgres:12.1
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: xsvbWkBdKeJFBYnVQrtR0VYXhOyq80pC
    volumes:
      - cf_postgres_data:/var/lib/postgresql/data/pgdata
      - ./initSql/:/docker-entrypoint-initdb.d/
      - ./backup/postgres:/opt/backup
    ports:
      - "5432:5432" 
    networks:
      - cb_factory
    restart: unless-stopped
  
  influxdb:
    image: influxdb:1.7.8
    volumes:
      - cf_influxdb_data:/var/lib/influxdb
      - ./backup/influxdb:/opt/backup
    ports: 
      - "8086:8086"
    networks:
      - cb_factory
    restart: unless-stopped

  analytica:
    image: analytica:latest
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb
#    ports:
#      - "4562:4562"
    networks:
      - cb_factory
    restart: unless-stopped
  
  designer:
    image: 'cf_designer:latest'
    environment:
      - JAVA_OPTS=-Xmx512m -Xms512m
      - DB_URL=//postgres:5432/chatbot
      - ANALYTICA_HOST=analytica
      - ANALYTICA_PORT=4562
      - INFLUXDB_URL=http://influxdb:8086
      - ANALYTICA_DBNAME=chatbot
      - devMode=true
    depends_on:
      - postgres
      - influxdb
      - analytica
    ports:
      - '127.0.0.1:8080:8080'
    networks:
      - cb_factory
    restart: unless-stopped
      
  runner_mars_dev:
    image: 'cf_runner:latest'
    environment:
      - DESIGNER_URL=http://designer:8080/designer/
      - ANALYTICA_HOST=analytica
      - ANALYTICA_PORT=4562
      - ANALYTICA_DBNAME=chatbot
      - API_KEY=3wqnHagLkbFsjTaW
    depends_on:
      - influxdb
      - analytica
    ports:
      - '127.0.0.1:8181:8080'
    volumes:
      - cf_runner_mars_dev_data:/opt/data
    networks:
      - cb_factory
    restart: unless-stopped

  runner_mars_prod:
    image: 'cf_runner:latest'
    environment:
      - DESIGNER_URL=http://designer:8080/designer/
      - ANALYTICA_HOST=analytica
      - ANALYTICA_PORT=4562
      - ANALYTICA_DBNAME=chatbot
      - API_KEY=@BDqoMD2dX2IQbkH
    depends_on:
      - influxdb
      - analytica
    ports:
      - '127.0.0.1:8182:8080'
    volumes:
      - cf_runner_mars_prod_data:/opt/data
    networks:
      - cb_factory
    restart: unless-stopped

  runner_oalia_dev:
    image: 'cf_runner:latest'
    environment:
      - DESIGNER_URL=http://designer:8080/designer/
      - ANALYTICA_HOST=analytica
      - ANALYTICA_PORT=4562
      - ANALYTICA_DBNAME=chatbot
      - API_KEY=LL3Slj5ZAUb2sUFz
    depends_on:
      - influxdb
      - analytica
    ports:
      - '127.0.0.1:8281:8080'
    volumes:
      - cf_runner_oalia_dev_data:/opt/data
    networks:
      - cb_factory
    restart: unless-stopped

  runner_oalia_prod:
    image: 'cf_runner:latest'
    environment:
      - DESIGNER_URL=http://designer:8080/designer/
      - ANALYTICA_HOST=analytica
      - ANALYTICA_PORT=4562
      - ANALYTICA_DBNAME=chatbot
      - API_KEY=cBKYShDhBxnB@yCo
    depends_on:
      - influxdb
      - analytica
    ports:
      - '127.0.0.1:8282:8080'
    volumes:
      - cf_runner_oalia_prod_data:/opt/data
    networks:
      - cb_factory
    restart: unless-stopped

  runner_rh_dev:
    image: 'cf_runner:latest'
    environment:
      - DESIGNER_URL=http://designer:8080/designer/
      - ANALYTICA_HOST=analytica
      - ANALYTICA_PORT=4562
      - ANALYTICA_DBNAME=chatbot
      - API_KEY=8HyemJ4SRlEABgQg
    depends_on:
      - influxdb
      - analytica
    ports:
      - '127.0.0.1:8381:8080'
    volumes:
      - cf_runner_rh_dev_data:/opt/data
    networks:
      - cb_factory
    restart: unless-stopped

  runner_rh_prod:
    image: 'cf_runner:latest'
    environment:
      - DESIGNER_URL=http://designer:8080/designer/
      - ANALYTICA_HOST=analytica
      - ANALYTICA_PORT=4562
      - ANALYTICA_DBNAME=chatbot
      - API_KEY=RqQ2Mb4@e@UR6X6V
    depends_on:
      - influxdb
      - analytica
    ports:
      - '127.0.0.1:8382:8080'
    volumes:
      - cf_runner_rh_prod_data:/opt/data
    networks:
      - cb_factory
    restart: unless-stopped

  runner_doe_change_dev:
    image: 'cf_runner:latest'
    environment:
      - DESIGNER_URL=http://designer:8080/designer/
      - ANALYTICA_HOST=analytica
      - ANALYTICA_PORT=4562
      - ANALYTICA_DBNAME=chatbot
      - API_KEY=PAWfBXzjZM7j3H7D
    depends_on:
      - influxdb
      - analytica
    ports:
      - '127.0.0.1:8481:8080'
    volumes:
      - cf_runner_doe_change_dev_data:/opt/data
    networks:
      - cb_factory
    restart: unless-stopped

  runner_doe_change_prod:
    image: 'cf_runner:latest'
    environment:
      - DESIGNER_URL=http://designer:8080/designer/
      - ANALYTICA_HOST=analytica
      - ANALYTICA_PORT=4562
      - ANALYTICA_DBNAME=chatbot
      - API_KEY=Bfy7FWkeT_enFu_b
    depends_on:
      - influxdb
      - analytica
    ports:
      - '127.0.0.1:8482:8080'
    volumes:
      - cf_runner_doe_change_prod_data:/opt/data
    networks:
      - cb_factory
    restart: unless-stopped

volumes:
  cf_postgres_data:
  cf_influxdb_data:
  cf_runner_mars_dev_data:
  cf_runner_mars_prod_data:
  cf_runner_oalia_dev_data:
  cf_runner_oalia_prod_data:
  cf_runner_rh_dev_data:
  cf_runner_rh_prod_data:
  cf_runner_doe_change_dev_data:
  cf_runner_doe_change_prod_data:
    
networks:
  cb_factory:
  