version: '3.5'

services:
  postgres:
    image: postgres
    container_name: cf_postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: 75rV7b5akp22dDs0sNdr9A2
    volumes:
      - cf_postgres_data:/var/lib/postgresql/data/pgdata
      - ./initSql/:/docker-entrypoint-initdb.d/
#    ports:
#      - "5433:5432" 
    networks:
      - cb_factory
    restart: unless-stopped
    
  designer:
    image: 'cf_designer:latest'
    container_name: cf_designer
    environment:
      - DB_URL=//postgres:5432/chatbot
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    networks:
      - cb_factory
    restart: unless-stopped
      
  runner1:
    image: 'cf_runner:latest'
    container_name: cf_runner_1
    environment:
      - designerUrl=http://designer:8080/
    ports:
      - '8081:8080'
    volumes:
      - cf_runner_1_data:/opt/data
    networks:
      - cb_factory
    restart: unless-stopped

volumes:
  cf_postgres_data:
  cf_runner_1_data:
    
networks:
  cb_factory:
  